"""Point d'entrée WSGI dédié à BÉCHÉFAA-Caisse.

Cette branche démarre exclusivement le nouveau backend clean_caisse.
Aucun import de l'ancien app.py / Wix / V1.
"""
from clean_caisse.app import app, db, ensure_order_schema, order_payload, load_catalog
from clean_caisse.kitchen_checklist import register_kitchen_checklist
from clean_caisse.history_modifier import register_history_modifier
from clean_caisse.customer_phase1 import register_customer_phase1
from clean_caisse.delivery_zones import register_delivery_zones
from clean_caisse.pos_quick_add import register_pos_quick_add
from clean_caisse.pos_touch_layout import register_pos_touch_layout
from clean_caisse.printing_phase1 import register_printing_phase1
from clean_caisse.history_print_buttons import register_history_print_buttons
from clean_caisse.phase1_audit_guard import register_phase1_audit_guard
from clean_caisse.history_add_product import register_history_add_product
from clean_caisse.printing_timestamp import register_printing_timestamp
from clean_caisse.product_admin_phase2 import register_product_admin_phase2
from clean_caisse.product_options_admin_phase2 import register_product_options_admin_phase2
from clean_caisse.options_diagnostic_phase2 import register_options_diagnostic_phase2
from clean_caisse.option_price_admin_phase23 import register_option_price_admin_phase23
from clean_caisse.option_add_test_phase23 import register_option_add_test_phase23
from clean_caisse.option_rules_test_phase23 import register_option_rules_test_phase23
from clean_caisse.category_diagnostic_phase24 import register_category_diagnostic_phase24
from clean_caisse.category_add_test_phase24 import register_category_add_test_phase24
from clean_caisse.category_rename_test_phase24 import register_category_rename_test_phase24
from clean_caisse.category_delete_test_phase24 import register_category_delete_test_phase24
from clean_caisse.category_admin_phase24 import register_category_admin_phase24
from clean_caisse.product_groups_diagnostic_phase25 import register_product_groups_diagnostic_phase25
from clean_caisse.product_group_remove_phase25 import register_product_group_remove_phase25
from clean_caisse.category_order_phase25 import register_category_order_phase25
from clean_caisse.product_order_phase25 import register_product_order_phase25
from clean_caisse.product_group_order_phase25 import register_product_group_order_phase25
from clean_caisse.product_group_rename_phase25 import register_product_group_rename_phase25
from clean_caisse.price_check_phase26 import register_price_check_phase26
from clean_caisse.order_price_guard_phase26 import register_order_price_guard_phase26
from clean_caisse.delivery_guard_phase27 import register_delivery_guard_phase27
from clean_caisse.order_update_guard_phase30 import register_order_update_guard_phase30
from clean_caisse.order_tax_snapshot_phase31 import register_order_tax_snapshot_phase31
from clean_caisse.catalog_summary_fast_phase32 import register_catalog_summary_fast_phase32
from clean_caisse.order_notifications_phase33 import register_order_notifications_phase33
from clean_caisse.cash_x_phase34 import register_cash_x_phase34
from clean_caisse.cash_z_phase35 import register_cash_z_phase35
from clean_caisse.phase35_ui_stability import register_phase35_ui_stability
from clean_caisse.table_core_phase36 import register_table_core_phase36
from clean_caisse.table_pos_phase36 import register_table_pos_phase36
from clean_caisse.table_print_phase36 import register_table_print_phase36
from clean_caisse.table_history_phase36 import register_table_history_phase36
from clean_caisse.z_lock_phase37 import register_z_lock_phase37
from clean_caisse.pos_quantity_phase38 import register_pos_quantity_phase38
from clean_caisse.payment_core_phase41 import register_payment_core_phase41
from clean_caisse.payment_history_ui_phase41 import register_payment_history_ui_phase41
from clean_caisse.service_mode_ui_phase42 import register_service_mode_ui_phase42
from clean_caisse.service_label_phase42 import register_service_label_phase42
from clean_caisse.payment_transactions_phase44 import register_payment_transactions_phase44
from clean_caisse.order_cancellation_phase44 import register_order_cancellation_phase44

register_catalog_summary_fast_phase32(app, load_catalog)
register_kitchen_checklist(app, db, ensure_order_schema, order_payload)
register_history_modifier(app, db, ensure_order_schema, order_payload)
register_pos_touch_layout(app, db)
register_customer_phase1(app, db, ensure_order_schema)
register_delivery_zones(app, db)
register_pos_quick_add(app)
register_printing_phase1(app, db, ensure_order_schema, order_payload)
register_history_print_buttons(app)
register_phase1_audit_guard(app, db, ensure_order_schema, order_payload)
register_history_add_product(app)
register_printing_timestamp(app, db)
register_product_admin_phase2(app, db)
register_product_options_admin_phase2(app, db)
register_options_diagnostic_phase2(app, db)
register_option_price_admin_phase23(app, db)
register_option_add_test_phase23(app, db)
register_option_rules_test_phase23(app, db)
register_category_diagnostic_phase24(app, db)
register_category_add_test_phase24(app, db)
register_category_rename_test_phase24(app, db)
register_category_delete_test_phase24(app, db)
register_category_admin_phase24(app, db)
register_product_groups_diagnostic_phase25(app, db)
register_product_group_remove_phase25(app, db)
register_category_order_phase25(app, db)
register_product_order_phase25(app, db)
register_product_group_order_phase25(app, db)
register_product_group_rename_phase25(app, db)
register_price_check_phase26(app, db)
register_order_price_guard_phase26(app, db)
register_delivery_guard_phase27(app, db)
register_order_update_guard_phase30(app, db)
register_order_tax_snapshot_phase31(app, db)
register_order_notifications_phase33(app)
register_cash_x_phase34(app, db, ensure_order_schema)
register_cash_z_phase35(app, db, ensure_order_schema)
register_phase35_ui_stability(app)
register_table_core_phase36(app, db)
register_table_pos_phase36(app, db)
register_table_print_phase36(app, db)
register_table_history_phase36(app)
register_z_lock_phase37(app, db, ensure_order_schema)
register_pos_quantity_phase38(app)
register_payment_core_phase41(app, db, ensure_order_schema)
register_payment_history_ui_phase41(app)
register_service_mode_ui_phase42(app)
register_service_label_phase42(app)
register_payment_transactions_phase44(app, db, ensure_order_schema)
register_order_cancellation_phase44(app, db, ensure_order_schema)
