"""Phase 4.4 — paramètres restaurant et matériel.

Page d'administration isolée. Elle réutilise l'API matériel validée sans
modifier la caisse, les tickets, la cuisine, l'historique, les paiements ou le Z.
"""
from flask import Response


def register_settings_admin_phase44(app):
    @app.get("/parametres")
    def settings_admin_phase44():
        html = r'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BÉCHÉFAA • Paramètres</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f5f7;color:#111827;font-family:Arial,sans-serif}.wrap{max-width:900px;margin:32px auto;padding:18px}.box{background:#fff;border-radius:16px;padding:22px;margin-bottom:16px;box-shadow:0 5px 20px #0001}h1,h2{margin-top:0}.muted{color:#667085;font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{font-size:13px;font-weight:800;display:block;margin-bottom:5px}input,select,button{width:100%;min-height:46px;border:1px solid #d0d5dd;border-radius:9px;padding:9px;font-size:15px}button{background:#111827;color:#fff;font-weight:900;cursor:pointer}.check{display:flex;gap:9px;align-items:center}.check input{width:auto;min-height:auto}.status{font-weight:800;margin-top:10px}.pill{display:inline-block;background:#ecfdf3;color:#027a48;border-radius:99px;padding:5px 9px;font-size:12px;font-weight:900}@media(max-width:650px){.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="box"><h1>Paramètres BÉCHÉFAA</h1><p class="muted">Configuration du poste de caisse. Cette page ne modifie pas les tickets déjà validés.</p></div><div class="box"><h2>Imprimante</h2><div class="grid"><div><label>Connexion</label><select id="pm"><option value="USB">USB</option><option value="NETWORK">Réseau Ethernet / Wi-Fi</option><option value="SYSTEM">Imprimante système</option></select></div><div><label>Marque</label><input id="pb"></div><div><label>Modèle</label><input id="pmodel"></div><div><label>Nom système / file d'impression</label><input id="pname" placeholder="Optionnel"></div><div><label>Adresse réseau</label><input id="phost" placeholder="Optionnel en USB"></div></div><p class="muted">Configuration actuelle de référence : <span class="pill">Epson TM-m30 USB</span></p></div><div class="box"><h2>Tiroir-caisse</h2><div class="grid"><div><label>Mode</label><select id="dm"><option value="DISABLED">Désactivé</option><option value="PRINTER_ESCPOS">Via imprimante ESC/POS</option><option value="LOCAL_BRIDGE">Passerelle locale</option></select></div><div><label>Règles</label><div class="check"><input id="cash" type="checkbox"><span>Ouverture automatique uniquement sur paiement espèces</span></div><div class="check" style="margin-top:9px"><input id="pin" type="checkbox"><span>PIN obligatoire pour ouverture manuelle</span></div></div></div><p class="muted">Le tiroir peut rester désactivé tant qu'il n'est pas physiquement installé.</p></div><div class="box"><button onclick="save()">Enregistrer les paramètres</button><div id="msg" class="status"></div></div></div><script>
const $=id=>document.getElementById(id);async function load(){try{let r=await fetch('/api/hardware/config-phase44',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Lecture impossible');$('pm').value=d.printer.mode;$('pb').value=d.printer.brand||'';$('pmodel').value=d.printer.model||'';$('pname').value=d.printer.name||'';$('phost').value=d.printer.host||'';$('dm').value=d.drawer.mode;$('cash').checked=!!d.drawer.open_on_cash;$('pin').checked=!!d.drawer.manual_pin_required;$('msg').textContent='Configuration chargée.'}catch(e){$('msg').textContent='Erreur : '+e.message}}
async function save(){$('msg').textContent='Enregistrement…';let body={printer:{mode:$('pm').value,brand:$('pb').value,model:$('pmodel').value,name:$('pname').value,host:$('phost').value},drawer:{mode:$('dm').value,open_on_cash:$('cash').checked,manual_pin_required:$('pin').checked}};try{let r=await fetch('/api/hardware/config-phase44',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Enregistrement impossible');$('msg').textContent='Paramètres enregistrés.'}catch(e){$('msg').textContent='Erreur : '+e.message}}load();
</script></body></html>'''
        return Response(html, content_type="text/html; charset=utf-8")
